#!/bin/dash

FILE="baremark.js"
README="README.md"

# Get size of staged 'baremark.js' module.
SIZE="$(git show ":$FILE" | wc -c)"

# Make sure that's the size given in staged README file.
FOUND="$(git show ":$README" | grep -oEw "currently [0-9]+ bytes")"

# We're good.
case "$FOUND" in "currently $SIZE bytes") exit 0 ; esac

# No, we're not.
printf '%s\n' \
       "Staged '$README' should contain current '$FILE' filesize!" \
       "    README says: '$FOUND'" \
       "    Should say : 'currently $SIZE bytes'" >&2

exit 1
#[eof]
